[tool.poetry]
name = "betahex"
version = "0.1.0"
description = ""
authors = ["Adrian Petrescu <adrian@apetre.sc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
rich = "^13.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
